preload = ["./scripts/md-loader.ts"]

[test]
preload = ["./scripts/md-loader.ts"]

[serve.static]
preload = ["./scripts/md-loader.ts"]
plugins = ["bun-plugin-tailwind", "./scripts/md-loader.ts"]
env = "BUN_PUBLIC_*"
